var students = [
  {
  "login": "aavor",
  "id": 2983861,
  "avatar_url": "https://avatars2.githubusercontent.com/u/2983861?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/aavor",
  "html_url": "https://github.com/aavor",
  "followers_url": "https://api.github.com/users/aavor/followers",
  "following_url": "https://api.github.com/users/aavor/following{/other_user}",
  "gists_url": "https://api.github.com/users/aavor/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/aavor/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/aavor/subscriptions",
  "organizations_url": "https://api.github.com/users/aavor/orgs",
  "repos_url": "https://api.github.com/users/aavor/repos",
  "events_url": "https://api.github.com/users/aavor/events{/privacy}",
  "received_events_url": "https://api.github.com/users/aavor/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Alfred Avor",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 19,
  "public_gists": 1,
  "followers": 3,
  "following": 4,
  "created_at": "2012-12-06T21:07:17Z",
  "updated_at": "2017-06-06T11:35:35Z"
},
{
  "login": "jcoster19",
  "id": 23200274,
  "avatar_url": "https://avatars1.githubusercontent.com/u/23200274?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/jcoster19",
  "html_url": "https://github.com/jcoster19",
  "followers_url": "https://api.github.com/users/jcoster19/followers",
  "following_url": "https://api.github.com/users/jcoster19/following{/other_user}",
  "gists_url": "https://api.github.com/users/jcoster19/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/jcoster19/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/jcoster19/subscriptions",
  "organizations_url": "https://api.github.com/users/jcoster19/orgs",
  "repos_url": "https://api.github.com/users/jcoster19/repos",
  "events_url": "https://api.github.com/users/jcoster19/events{/privacy}",
  "received_events_url": "https://api.github.com/users/jcoster19/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Jack Coster",
  "company": null,
  "blog": "",
  "location": "Arlington, VA",
  "email": null,
  "hireable": null,
  "bio": "GW coding bootcamp student\r\n\r\nFull Stack web dev",
  "public_repos": 20,
  "public_gists": 1,
  "followers": 1,
  "following": 0,
  "created_at": "2016-11-01T21:16:16Z",
  "updated_at": "2017-06-24T14:41:27Z"
},{
  "login": "minicooperj",
  "id": 23705543,
  "avatar_url": "https://avatars1.githubusercontent.com/u/23705543?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/minicooperj",
  "html_url": "https://github.com/minicooperj",
  "followers_url": "https://api.github.com/users/minicooperj/followers",
  "following_url": "https://api.github.com/users/minicooperj/following{/other_user}",
  "gists_url": "https://api.github.com/users/minicooperj/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/minicooperj/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/minicooperj/subscriptions",
  "organizations_url": "https://api.github.com/users/minicooperj/orgs",
  "repos_url": "https://api.github.com/users/minicooperj/repos",
  "events_url": "https://api.github.com/users/minicooperj/events{/privacy}",
  "received_events_url": "https://api.github.com/users/minicooperj/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Cary Cooper",
  "company": null,
  "blog": "",
  "location": "Washington D.C. Metro Area",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 22,
  "public_gists": 0,
  "followers": 7,
  "following": 10,
  "created_at": "2016-11-23T17:45:04Z",
  "updated_at": "2017-06-22T16:33:40Z"
}
]

module.exports = students;
